### ISSUE TITLE
Please add How to Compile in README.md

### ISSUE THREAD

**Issue by midhunvnadh** [ibanezbass/gta3xlwifi-infinity-kernel#2]
I couldn't figure out how you could build the zImage since it is for 32-bit kernel.
Thank you. Please add the info. You did a great job with the kernel.

**Comment by ibanezbass** [comment]
The kernel is 64 bit. The OS is 32 bit. You use the build_kernel.sh to compile.

**Comment by midhunvnadh** [comment]
> The kernel is 64 bit. The OS is 32 bit. You use the build_kernel.sh to compile.

I think you use the AnyKernel3 and you have an zImage instead of a Image

**Comment by ibanezbass** [comment]
I am using AnyKernel3 after I’ve built the image. There is an output named “Image” and “Image.gz”. Just take Image, rename to zImage, and move to the root of AnyKernel.

**Comment by midhunvnadh** [comment]
Okay ! Thank you !
https://forum.xda-developers.com/galaxy-tab-a/development/ubports-ubuntu-touch-sm-t510-t515-t4146417
I made this. Perhaps you can check this out !
